# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed15d5d0fecaddd41059119bf6f26b8734505b32a2a0b9eb07faf4d7a11ef5187b09d3e7c435a314705ff395ec8e06f2ae917cf4e85a2aa1ad660e7b25c5bef1
  admin_username: 'admin'
  admin_password: 'test'
  s3_key: <%= ENV['S3_KEY'] %>
  s3_secret: <%= ENV['S3_SECRET'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>

test:
  secret_key_base: 4e1946719d5bbf78646391340edd0321255abb1758b3a4cded97ce683daac81fc05ebbd886dddf96fdeae5458193cc10f768e6379f1473e79ec7f730996c974f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_username: <%= ENV['ADMIN_USERNAME'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  s3_key: <%= ENV['S3_KEY'] %>
  s3_secret: <%= ENV['S3_SECRET'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
